pipeline {
    agent any

    environment {
        INVENTORY_FILE = 'devops/Ansible/hosts.ini'
        PLAYBOOK_FILE  = 'devops/Ansible/playbook.yml'
        SSH_CRED_ID    = 'target-servers-ssh-key'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Ansible Lint & Syntax Check') {
            steps {
                sh "ansible-playbook -i ${env.INVENTORY_FILE} ${env.PLAYBOOK_FILE} --syntax-check"
            }
        }

        stage('Ansible Deploy') {
            steps {
                
                withCredentials([
                    file(credentialsId: 'ansible-vars-file', variable: 'VARS_FILE_PATH'),
                    string(credentialsId: 'sudo-password', variable: 'SUDO_PASS')
                ]) {
                    script {
                        env.ANSIBLE_HOST_KEY_CHECKING = 'False'
                        env.ANSIBLE_ROLES_PATH        = 'devops/Ansible/roles'
                        
                        sh "mkdir -p devops/Ansible/group_vars/all"
                        sh "cp \${VARS_FILE_PATH} devops/Ansible/group_vars/all/vars.yml"
                    }

                    ansiblePlaybook(
                        playbook: "${env.PLAYBOOK_FILE}",
                        inventory: "${env.INVENTORY_FILE}",
                        credentialsId: "${env.SSH_CRED_ID}",
                        vaultCredentialsId: 'ansible-vault-password',
                        extraVars: [
                            'jenkins_build_num': "${env.BUILD_NUMBER}",
                            'jenkins_job_name': "${env.JOB_NAME}",
                            'deploy_env': "production"
                            'ansible_become_password': "${SUDO_PASS}" 
                        ]
                    )
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}

