# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Глобальний образ
  config.vm.box = "gusztavvargadr/ubuntu-server-2404-lts"
  config.vm.box_version = "2506.0.0"

  
  # 1. ПОТОЧНА КЕРУЮЧА ВМ
  config.vm.define "default", primary: true do |main|
    main.vm.network "private_network", ip: "192.168.33.10"
    main.vm.hostname = "vm-main"
    main.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = "2"
    end
    # Скрипт Java коментуємо, бо вона вже встановлена
    # main.vm.provision "shell", inline: "apt-get update && apt-get install -y openjdk-17-jdk"
  end

  
  # 2. НОВА ВМ ФРОНТЕНД (React JS + Nginx)
  config.vm.define "vm_front" do |front|
    front.vm.network "private_network", ip: "192.168.33.11"
    front.vm.hostname = "vm-front"
    front.vm.network "forwarded_port", guest: 80, host: 8082, host_ip: "127.0.0.1"
    front.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "1"
    end
  end

  
  
  # 3. НОВА ВМ БЕКЕНД (Java 17 + Maven)
  config.vm.define "vm_back" do |back|
    back.vm.network "private_network", ip: "192.168.33.12"
    back.vm.hostname = "vm-back"
    back.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "1"
    end
    back.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y openjdk-17-jdk
    SHELL
  end

  
  
  # 4. НОВА ВМ БАЗА ДАНИХ (MariaDB)
  config.vm.define "vm_db" do |db|
    db.vm.network "private_network", ip: "192.168.33.13"
    db.vm.hostname = "vm-db"
    db.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end
  end
end

