---
- name: Stop and remove old cAdvisor container
  community.docker.docker_container:
    name: cadvisor
    state: absent

- name: Download cAdvisor binary
  get_url:
    url: https://github.com
    dest: /usr/local/bin/cadvisor
    mode: '0755'

- name: Create systemd service for cAdvisor
  copy:
    dest: /etc/systemd/system/cadvisor.service
    content: |
      [Unit]
      Description=cAdvisor Exporter
      After=network.target docker.service containerd.service

      [Service]
      Type=simple
      ExecStart=/usr/local/bin/cadvisor --port=8081 --docker_only=true
      Restart=always
      RestartSec=10

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd, enable and start cAdvisor service
  systemd:
    name: cadvisor
    state: restarted
    daemon_reload: yes
    enabled: yes

