---
- name: Run cAdvisor container
  community.docker.docker_container:
    name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    state: started
    restart_policy: always
    privileged: true
    published_ports:
      - "8081:8080"
    ipc_mode: host
    pid_mode: host
    user: "0:0"
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /sys:/sys:ro
      - /dev/disk/:/dev/disk:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/run:/var/run:ro
      - /run/containerd:/run/containerd:ro
      - /etc/machine-id:/etc/machine-id:ro
    devices:
      - /dev/kmsg
    env:
      CADVISOR_HEALTHCHECK_URL: "http://localhost:8080/healthz"
