---
- name: Log in to Docker Hub
  community.docker.docker_login:
    username: "dima70593"
    password: "{{ docker_hub_password }}"

- name: Create directory for DB init scripts on target host
  ansible.builtin.file:
    path: /var/lib/teachua/db_init
    state: directory
    mode: '0755'


- name: Copy data.sql to target VM
  ansible.builtin.copy:
    src: "../../../data.sql"
    dest: /var/lib/teachua/db_init/data.sql
    mode: '0644'

- name: Run MariaDB Container
  community.docker.docker_container:
    name: teach-ua-db
    image: "mariadb:10.11"
    state: started
    restart_policy: always
    networks:
      - name: teachua_network
    published_ports:
      - "3306:3306"
    volumes:
      - "/var/lib/mysql:/var/lib/mysql"
      - "/var/lib/teachua/db_init:/docker-entrypoint-initdb.d"
    env:
      MYSQL_DATABASE: "teachua"
      MYSQL_USER: "{{ db_user_from_vars }}"
      MYSQL_PASSWORD: "{{ db_password_from_vars }}"
      MYSQL_ROOT_PASSWORD: "{{ db_root_password_from_vars }}"

