---
- name: Install Docker prerequisites
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-pip
      - python3-docker
    state: present
    update_cache: yes

- name: Install Docker Engine
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Ensure Docker is started and enabled
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes

- name: Create internal Docker network for app
  community.docker.docker_network:
    name: teachua_network
