---
- name: Forcefully free port 3000 from any blocking process
  ansible.builtin.shell: "fuser -k 3000/tcp || true"
  ignore_errors: yes

- name: Stop any rogue docker container using port 3000
  ansible.builtin.shell: "docker ps -q --filter publish=3000 | xargs -r docker stop"
  ignore_errors: yes

- name: Remove old frontend container
  community.docker.docker_container:
    name: teach-ua-frontend
    state: absent
  ignore_errors: yes


- name: Run Frontend Container
  community.docker.docker_container:
    name: teach-ua-frontend
    image: "dima70593/teach-ua-frontend:{{ jenkins_build_num }}"
    state: started
    restart_policy: always
    pull: true
    networks:
      - name: teachua_network
    published_ports:
      - "3000:3000"


- name: Clean up old unused Docker images to save disk space
  ansible.builtin.shell: "docker system prune -af"


- name: Configure Nginx as reverse proxy
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_dest }}"
  notify: Restart nginx


- name: Enable Nginx site
  ansible.builtin.file:
    src: "{{ nginx_conf_dest }}"
    dest: "{{ nginx_sites_enabled }}"
    state: link

