---
- name: Deploy Teach UA Application via Docker
  hosts: target_server
  become: true

  roles:
    - role: docker_install
    - role: database
    - role: backend
    - role: frontend
    - role: node_exporter

- name: Deploy Prometheus and Grafana to Monitoring Server
  hosts: monitoring_servers
  become: true
  roles:
    - docker_install
    - monitoring
